### ISSUE TITLE
lint 도입

### ISSUE THREAD

**Issue by whilemouse** [whilemouse/FashionC#9]
- [ ] lint 자체가 필요할지? 코딩 컨벤션과 규칙을 맞추기에 좋은데, 배우는 시간이 필요하긴 함
- [ ] express 프로젝트도 lint가 필요할지
- [x] fasion-react/package.json에 eslintConfig를 그대로 사용할 지 다른걸 사용할지

- 기본에 의거해서 했으면 하는 생각, 초기에 이것저것 셋팅이 많으면 후반에 좋지만 그만큼의 러닝커브도 많이 발생. 기본 셋팅 위주로 개발진행하되 추후 필요하다고 생각되는 것들은 추가 진행 - 민서 -

**Comment by whilemouse** [comment]
lint 자체가 필요할지? 코딩 컨벤션과 규칙을 맞추기에 좋은데, 배우는 시간이 필요하긴 함
- 공부 목적으로 하는거면 해보는거 도움된다고 생각함

**Comment by kangminser** [comment]
hey testing comment

**Comment by kangminser** [comment]
기본에 의거해서 했으면 하는 생각, 초기에 이것저것 셋팅이 많으면 후반에 좋지만 그만큼의 러닝커브도 많이 발생. 기본 셋팅 위주로 개발진행하되 추후 필요하다고 생각되는 것들은 추가 진행

**Comment by whilemouse** [comment]
기본에 있는 eslintConfig 사용으로 결정
